# Generated by Django 5.0.6 on 2024-10-22 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_areaserviced_remove_client_zip_client_zipcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaserviced',
            old_name='zipcodes',
            new_name='zipcode',
        ),
    ]
