# Generated by Django 5.0.6 on 2024-11-23 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_address_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='below_poverty_line',
            field=models.BooleanField(blank=True, help_text='Please select Yes or No', null=True, verbose_name='Does the client live below the poverty line (below $1,250 a month)?'),
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Please provide the clients date of birth', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='client',
            name='disabled',
            field=models.BooleanField(blank=True, help_text='Please select Yes or No', null=True, verbose_name='Is the client disabled?'),
        ),
        migrations.AddField(
            model_name='client',
            name='homeless',
            field=models.BooleanField(blank=True, help_text='Please select Yes or No', null=True, verbose_name='Is the client homeless?'),
        ),
        migrations.AddField(
            model_name='client',
            name='veteran',
            field=models.BooleanField(blank=True, help_text='Please select Yes or No', null=True, verbose_name='Is the client a veteran?'),
        ),
        migrations.AlterField(
            model_name='client',
            name='area_serviced',
            field=models.ForeignKey(help_text='Please select from the options provided', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.areaserviced', verbose_name='Please select the area the client lives in'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ethnicity',
            field=models.CharField(choices=[('AS', 'Asian'), ('BL', 'Black'), ('HI', 'Hispanic'), ('WH', 'White'), ('OT', 'Other')], default='OT', help_text='Please select from the options provided', max_length=2, verbose_name='What is the clients ethnicity?'),
        ),
    ]
