# Generated by Django 5.0.6 on 2024-11-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_client_birth_date_client_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Please select Yes or No', verbose_name='Is the client active?'),
        ),
    ]
