# Generated by Django 5.0.6 on 2024-11-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('MA', 'Male'), ('FE', 'Female')], help_text='Please select from the options provided', max_length=2, null=True, verbose_name='What is the clients gender?'),
        ),
    ]
