# Generated by Django 5.0.6 on 2024-10-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='image',
        ),
    ]
