# Generated by Django 5.0.6 on 2024-11-23 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_areaserviced_name_alter_areaserviced_zipcode_and_more'),
        ('equipment', '0003_remove_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='barcode',
            field=models.CharField(blank=True, help_text='Please provide the equipment barcode or serial number', max_length=100, null=True, verbose_name='Equipment Barcode or Serial Number (Optional)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, help_text='Please provide the equipment description', null=True, verbose_name='Equipment Description (Optional)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(help_text='Please provide the equipment name', max_length=100, verbose_name='Equipment Name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='stock',
            field=models.IntegerField(default=0, help_text='Please provide the equipment stock count', verbose_name='Equipment Stock'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='Please select the client associated with the order', on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client associated with the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.ForeignKey(help_text='Please select the equipment associated with the order', on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Equipment associated with the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Please provide the equipment quantity', verbose_name='Equipment Quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RT', 'Rented'), ('RU', 'Returned')], default='RT', help_text='Please select the order status', max_length=2, verbose_name='Order Status'),
        ),
    ]
