# Generated by Django 5.0.6 on 2024-11-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_dmeorder_rental_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmeorder',
            options={'verbose_name': 'Durables Medical Equipment Order', 'verbose_name_plural': 'Durables Medical Equipment Orders'},
        ),
        migrations.AddField(
            model_name='dmeorder',
            name='approximate_time_needed',
            field=models.TextField(blank=True, help_text='Please provide the approximate time needed', null=True, verbose_name='Approximate Time Needed (Optional)'),
        ),
    ]
