# Generated by Django 5.0.6 on 2024-11-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_dmeorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmeorder',
            name='approximate_time_needed',
        ),
        migrations.AddField(
            model_name='dmeorder',
            name='time_needed',
            field=models.CharField(choices=[('1W', '1 Week'), ('2W', '2 Weeks'), ('1M', '1 Month'), ('3M', '3 Months'), ('6M', '6 Months'), ('1Y', '1 Year')], default='1W', help_text='Please select the time needed for the equipment', max_length=2, verbose_name='Time Needed'),
        ),
    ]
