# Generated by Django 5.0.6 on 2024-11-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplies',
            options={'verbose_name_plural': 'Supplies'},
        ),
        migrations.AlterModelOptions(
            name='suppliesorder',
            options={'verbose_name_plural': 'Supply Orders'},
        ),
    ]
