# Generated by Django 5.0.6 on 2024-11-23 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_areaserviced_name_alter_areaserviced_zipcode_and_more'),
        ('supplies', '0002_alter_supplies_options_alter_suppliesorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='description',
            field=models.TextField(blank=True, help_text='Please provide the supply description', null=True, verbose_name='Supply Description (Optional)'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='name',
            field=models.CharField(help_text='Please provide the supply name', max_length=100, verbose_name='Supply Name'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='price',
            field=models.FloatField(blank=True, help_text='Please provide the supply price', null=True, verbose_name='Supply Price'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Please provide the supply quantity', verbose_name='Supply Quantity'),
        ),
        migrations.AlterField(
            model_name='suppliesorder',
            name='client',
            field=models.ForeignKey(help_text='Please select the client associated with the order', on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client associated with the order'),
        ),
        migrations.AlterField(
            model_name='suppliesorder',
            name='delivery_date',
            field=models.DateField(help_text='Please provide the supply delivery date', verbose_name='Supply Delivery Date'),
        ),
        migrations.AlterField(
            model_name='suppliesorder',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Please provide the supply quantity', verbose_name='Supply Quantity'),
        ),
        migrations.AlterField(
            model_name='suppliesorder',
            name='supplies',
            field=models.ForeignKey(help_text='Please select the supply associated with the order', on_delete=django.db.models.deletion.CASCADE, to='supplies.supplies', verbose_name='Supply associated with the order'),
        ),
    ]
