# Generated by Django 5.0.6 on 2024-11-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_supplies_description_alter_supplies_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplies',
            name='price',
        ),
    ]
