# Generated by Django 5.0.6 on 2024-11-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_remove_supplies_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliesorder',
            name='supplies_other',
            field=models.CharField(blank=True, help_text='Please provide the supply name if not listed above', max_length=256, null=True, verbose_name='Other supplies not listed above'),
        ),
        migrations.AlterField(
            model_name='suppliesorder',
            name='delivery_date',
            field=models.DateField(help_text='Please provide the supply delivery date in the following format with dashes (year-month-date) or use the date selected on the right.', verbose_name='Supply Recieved Date'),
        ),
    ]
