# Generated by Django 5.0.6 on 2024-11-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_suppliesorder_supplies_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliesorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='suppliesorder',
            name='supplies',
        ),
        migrations.RemoveField(
            model_name='suppliesorder',
            name='supplies_other',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Please provide the supply quantity', verbose_name='Supply Quantity')),
                ('other_notes', models.CharField(blank=True, help_text='Please provide any other notes', max_length=256, null=True, verbose_name='Other notes')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.suppliesorder')),
                ('supplies', models.ForeignKey(help_text='Please select the supply associated with the order', on_delete=django.db.models.deletion.CASCADE, to='supplies.supplies', verbose_name='Supply associated with the order')),
            ],
        ),
    ]
