# Generated by Django 5.0.6 on 2024-11-21 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_address_alter_client_city_and_more'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Evaluation Survey', 'verbose_name_plural': 'Evaluation Surveys'},
        ),
        migrations.AddField(
            model_name='survey',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='comments',
            field=models.TextField(blank=True, help_text='Please provide any additional comments', null=True, verbose_name='Additional Comments'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='meet_expectations',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Please select Yes or No', verbose_name='Did we meet your expectations?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='refer_friends',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Please select Yes or No', verbose_name='Would you refer your friends to our service?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='service_impact',
            field=models.TextField(blank=True, help_text='Please provide any additional comments', null=True, verbose_name='How did the service impact you?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='volunteer_helpful',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Please select Yes or No', verbose_name='Was the volunteer helpful?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='survior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survior'),
        ),
    ]
