# Generated by Django 5.0.6 on 2024-11-21 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_address_alter_client_city_and_more'),
        ('survey', '0002_survior_alter_survey_options_survey_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survior',
            options={'verbose_name': 'Survior Profile', 'verbose_name_plural': 'Surviors Profiles'},
        ),
        migrations.CreateModel(
            name='ClientSurvey2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uti_lastyear', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Please select Yes or No', verbose_name='Have you had a Urinary Tract Infection (UTI) in the last year?')),
                ('medical_treatment', models.CharField(choices=[('Doctor', 'Doctor'), ('ER', 'ER'), ('Urgent Care', 'Urgent Care'), ('N/A', 'N/A')], default='N/A', help_text='Please select the appropriate option', max_length=20, verbose_name='If you sought medical care, did you have to see a doctor or go to the ER?')),
                ('distance_to_healthcare', models.CharField(choices=[('Within a mile', 'Within a mile'), ('Further than a mile but within five miles', 'Further than a mile but within five miles'), ('Further than five miles', 'Further than five miles')], default='Within a mile', help_text='Please select the appropriate option', max_length=50, verbose_name='How far away from health care do you live?')),
                ('used_leakage_items', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Please select Yes or No', verbose_name='Have you ever used items to assist with leakage other than adult diapers, bladder pads/products (such as towels, sheets, washcloths etc.)?')),
                ('helped_leave_home', models.CharField(choices=[('Doctors appointments', 'Go to doctors appointments'), ('Shop', 'Shop'), ('Attend church', 'Attend church'), ('Socialize', 'Socialize'), ('Other', 'Other')], default='Doctors appointments', help_text='Please select the appropriate option', max_length=50, verbose_name='Has having incontinent products helped you to leave home more to:')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('survior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survior')),
            ],
            options={
                'verbose_name': '2024 Client Survey',
                'verbose_name_plural': '2024 Client Surveys',
            },
        ),
    ]
