# Generated by Django 5.0.6 on 2024-11-21 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_survior_options_clientsurvey2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survior',
            new_name='Surveyor',
        ),
    ]
