# Generated by Django 5.0.6 on 2024-11-22 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_address_alter_client_city_and_more'),
        ('survey', '0004_rename_survior_surveyor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsurvey2024',
            name='client',
        ),
        migrations.AddField(
            model_name='clientsurvey2024',
            name='area_serviced',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.areaserviced'),
        ),
    ]
