# Generated by Django 5.0.6 on 2024-11-23 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_survey_survior_survey_area_serviced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyor',
            options={'verbose_name': 'Surveyor Profile', 'verbose_name_plural': 'Surveyors Profiles'},
        ),
        migrations.RemoveField(
            model_name='clientsurvey2024',
            name='area_serviced',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='area_serviced',
        ),
        migrations.AddField(
            model_name='clientsurvey2024',
            name='other_comments',
            field=models.TextField(blank=True, help_text='Please provide any additional comments', null=True, verbose_name='Additional Comments'),
        ),
        migrations.AddField(
            model_name='clientsurvey2024',
            name='zipcodes',
            field=models.CharField(blank=True, help_text='Please provide your zipcode', max_length=10, null=True, verbose_name='Zipcode'),
        ),
        migrations.AddField(
            model_name='survey',
            name='zipcode',
            field=models.CharField(blank=True, help_text='Please provide your zipcode', max_length=10, null=True, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='clientsurvey2024',
            name='survior',
            field=models.ForeignKey(blank=True, help_text='Please select the surveyor', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyor', verbose_name='Surveyor'),
        ),
    ]
