# Generated by Django 5.0.6 on 2024-11-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_surveyor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpedLeaveHomeChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientsurvey2024',
            name='helped_leave_home',
        ),
        migrations.AddField(
            model_name='clientsurvey2024',
            name='helped_leave_home',
            field=models.ManyToManyField(help_text='Please select the appropriate options', to='survey.helpedleavehomechoices', verbose_name='Has having incontinent products helped you to leave home more to:'),
        ),
    ]
