# Generated by Django 5.0.6 on 2024-11-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_helpedleavehomechoices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsurvey2024',
            name='helped_leave_home',
        ),
        migrations.DeleteModel(
            name='HelpedLeaveHomeChoices',
        ),
    ]
