# Generated by Django 5.0.6 on 2024-11-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_remove_survey_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTreatmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_treatment', models.JSONField(default=list, help_text='Please select the appropriate options', verbose_name='If you sought medical care, did you have to see a doctor or go to the ER?')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientsurvey2024',
            name='medical_treatment',
        ),
    ]
