# Generated by Django 5.0.6 on 2024-11-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_medicaltreatmentquestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsurvey2024',
            old_name='survior',
            new_name='surveyor',
        ),
        migrations.RenameField(
            model_name='clientsurvey2024',
            old_name='zipcodes',
            new_name='zipcode',
        ),
    ]
