# Generated by Django 5.0.6 on 2024-11-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_zipcodesurvey_alter_clientsurvey2024_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsurvey2024',
            name='_zipcode',
            field=models.ForeignKey(blank=True, help_text='Please provide your zipcode', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.zipcodesurvey', verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='clientsurvey2024',
            name='zipcode',
            field=models.CharField(blank=True, help_text='Please provide your zipcode', max_length=10, null=True, verbose_name='Zipcode'),
        ),
    ]
