# Generated by Django 5.0.6 on 2024-11-24 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_clientsurvey2024__zipcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsurvey2024',
            name='_zipcode',
        ),
        migrations.AlterField(
            model_name='clientsurvey2024',
            name='zipcode',
            field=models.ForeignKey(blank=True, help_text='Please provide your zipcode', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.zipcodesurvey', verbose_name='Zipcode'),
        ),
    ]
