# Generated by Django 5.0.6 on 2024-11-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_alter_clientsurvey2024_used_leakage_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsurvey2024',
            name='distance_to_healthcare',
            field=models.CharField(choices=[('Within a mile', 'Within a mile'), ('Further than a mile but within five miles', 'Further than a mile but within five miles'), ('Further than five miles', 'Further than five miles')], help_text='Please select the appropriate option', max_length=50, verbose_name='How far away from health care do you live?'),
        ),
    ]
