# Generated by Django 5.0.6 on 2024-11-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_alter_clientsurvey2024_distance_to_healthcare'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsurvey2024',
            name='date',
            field=models.DateField(blank=True, help_text='Please provide the date of the survey', null=True, verbose_name='Date of Survey'),
        ),
    ]
